### ISSUE TITLE
[New req] ทางลูกค้าต้องการให้ตู้หยอดเหรียญมีจำนวนเหรียญอยู่จำกัด

### ISSUE THREAD

**Issue by nitipatl** [beeforce/problem-vending-machine#1]
ตามความต้องการแรกเริ่มของเรานั้นไม่ได้มีการระบุว่าจำนวนเหรียญประเภทต่าง ๆ ของตู้มีอยู่เท่าไร
ดังนั้นสิ่งที่ลูกค้าอยากได้คือ ตู้ต้องสามารถระบุจำนวนเหรียญที่สามารถทอนได้ของเหรียญประเภทต่าง ๆ
โดยจำนวนจะต้องถูกลดลงหรือเพิ่มขึ้นไปเรื่อย ๆ เมื่อผู้ซื้อใข้งานเครื่อง

**ตัวอย่าง**  จำนวนเหรียญที่ในตู้มีตั้งต้นคือ

| ประเภทเหรียญ |  10  |  5   |  2   |  1   |
|--------------|-----|----|---|---|
| จำนวนที่ตู้มี | 5 | 10 | 3 | 10 |

เมื่อมีผู้ซื้อมาหยอดเหรียญ 20 บาท (ใช้เหรียญ 10 บาท จำนวน 2 เหรียญ) เพื่อซื้อน้ำราคา 15 บาท
จะมีเหรียญคงเหลือจากการทอนเงินไปดังนี้

| ประเภทเหรียญ |  10  |  5   |  2   |  1   |
|--------------|-----|----|---|---|
| จำนวนที่ตู้มี | 7 | 9 | 3 | 10 |

นั่นคือตู้ได้รับเหรียญ 10 เพิ่มมา 2 เหรียญจากเดิม 5 เหรียญรวมเป็น 7 เหรียญ และ ได้ทำการทอนเหรียญ 5 ออกไป 1 เหรียญคงเหลือจาก 10 เหรียญ เป็น 9 เหรียญ

**หากตู้ไม่สามารถทอนเหรียญได้ ให้ทำการคืนเงินที่ผู้ซื้อหยอดมาทั้งหมด และ ยกเลิกการขายทันที**

ถ้ามีคำถามเกี่ยวกับเงื่อนไข ถามได้ใน issue นี้ครับ ;)

**Comment by beeforce** [comment]
ถ้าสมมุติว่า เหรียญ10 ไม่พอถอน เราสามารถใช้เหรียญอื่นทอนได้ไหมครับ เช่น หยอดเหรียญ 5 ไป 30 บาท แล้วซื้อน้ำ 15 บาท จะได้ทอน เหรียญ 10 กับ เหรียญ 5 อย่างละหนึ่งเหรียญ ในกรณีนี้สามารถใช้เหรียญอื่นทอนแทนเหรียญ10ได้ไหมครับ

**Comment by nitipatl** [comment]
ได้ครับ ถ้าเหรียญที่ใหญ่กว่ามีไม่พอทอน ก็ให้ทอนตามลำดับเพราะคนซื้อก็ไม่ได้อยากได้เหรียญย่อย ๆ 
เคสที่ไม่สามารถทอนได้คือเคสที่เหรียญทุกชนิดมีไม่พอทอนครับ
